### ISSUE TITLE
Does not work with document-register-element polyfill

### ISSUE THREAD

**Issue by warpech** [matthewp/read-time#4]
As reported in https://github.com/Starcounter/level1/pull/4228#issuecomment-311207443, `read-time` does not work well with WebReflection `document-register-element` polyfill because of https://github.com/WebReflection/document-register-element#upgrading-the-constructor-context.

A quick fix from on our side is: https://github.com/StarcounterApps/KitchenSink/commit/df4199dc075cb45fae3977e91ce82d4bca69ccce

Please consider including it in `read-time`

**Comment by matthewp** [comment]
Hey! Sorry I missed this, is this still needed?

**Comment by warpech** [comment]
I will have to let you judge this, because I actually do not use you custom element (yet?). I discovered it by a chance when evaluating the https://github.com/WebReflection/document-register-element polyfill. 

I think that it would be nice if your custom element works with both polyfills that I know of:

- https://github.com/WebReflection/document-register-element
- https://github.com/webcomponents/webcomponentsjs

**Comment by matthewp** [comment]
Missed this, but since all browsers support custom elements now, this is no longer needed.
